# Generated by Django 4.2.7 on 2023-12-12 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_userchildreninformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchildreninformation',
            name='oms',
        ),
        migrations.RemoveField(
            model_name='userchildreninformation',
            name='snils',
        ),
        migrations.RemoveField(
            model_name='userchildreninformation',
            name='svidetelstvo',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='passport',
        ),
        migrations.AddField(
            model_name='userchildreninformation',
            name='birthdate',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
