# Generated by Django 4.2.7 on 2023-12-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_remove_userchildreninformation_oms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchildreninformation',
            name='birthdate',
            field=models.DateTimeField(),
        ),
    ]
