# Generated by Django 4.2.7 on 2023-12-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_alter_userchildreninformation_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='specialist',
            name='phone',
            field=models.CharField(default='89115926942', max_length=255),
        ),
    ]
