# Generated by Django 4.2.7 on 2023-12-13 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_alter_specialist_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SpecialistSchedule', to='record.specialist')),
            ],
        ),
    ]
