# Generated by Django 4.2.7 on 2023-12-13 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('record', '0010_specialistschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='specialistschedule',
            options={'ordering': ('date',)},
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record1', to='record.userchildreninformation')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record4', to='record.specialistschedule')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record2', to='record.direction')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record3', to='record.specialist')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record5', to='record.recordstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
    ]
