# Generated by Django 4.2.7 on 2023-12-13 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0011_recordstatus_alter_specialistschedule_options_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='date',
            new_name='record_date',
        ),
        migrations.AddField(
            model_name='record',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
